on:
    push:
      tags:
      - 'v*'
  
name: Upload Release Asset
  
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
          - name: Download latest artifact
            uses: actions/download-artifact@v3
            with:
              name: ArtemisMC-Plugin
    
          - name: Release with Notes
            uses: softprops/action-gh-release@v1
            with:
              files: ArtemisMC-Plugin.zip
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  