on:
    push:
      branch:
        - workflows
  
name: Upload Release
  
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
          - name: Setup .NET
            uses: actions/setup-dotnet@v1
            with:
              dotnet-version: '7.0.x'
    
          - name: Clone
            uses: actions/checkout@v2
    
          - name: Build
            run: dotnet publish -c Release src
    
          - name: Upload
            uses: actions/upload-artifact@v3
            with:
              path: src/Artemis.Plugins.Games.Minecraft/bin/x64/Release/net7.0/publish
              name: ArtemisMC-Plugin
              
          - name: Download latest artifact
            uses: actions/download-artifact@v3
            with:
              name: ArtemisMC-Plugin
              path: plugin

          - name: Zip Artifact
            run: |
              ls -l
              ls -l plugin
              zip -r ArtemisMC-Plugin.zip plugin/*
    
          - name: Release with Notes
            uses: softprops/action-gh-release@v1
            with:
              files: ArtemisMC-Plugin.zip
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  